[package]
name = "gnu"
version = "0.1.0"
edition = "2021"

[lib]
name = "gnu"
path = "lib.rs"
crate-type = ["rlib"]  # 声明为静态库

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.170"
nix = { version = "0.29", features = ["fs"] } 
bitflags = "1.3"
